### ISSUE TITLE
结果

### ISSUE THREAD

**Issue by JunYannnn** [huyingxi/Question-Classification#3]
您好！请问您最后测试集500个句子测试的结果，准确率是98.5%吗？

**Comment by huyingxi** [comment]
您好，这份代码只有96.6.
另外我自己做实验有98.5

**Comment by JunYannnn** [comment]
我是用5500的训练数据（实际是5452个句子），用的500的测试数据，用您的代码得到的测试acc为98.5%，请问，您96.6是怎么得到的？

**Comment by JunYannnn** [comment]
我用的训练数据集是TREC5500的那个Trainingset

**Comment by huyingxi** [comment]
查了一下训练日志，是可以上98的，在5000的数据集上

**Comment by JunYannnn** [comment]
好的，非常感谢～～

**Comment by huyingxi** [comment]
不客气
